server.port=8083

spring.application.name=disruption-service

# Dedicated Database for Disruption Service
spring.datasource.url=jdbc:postgresql://localhost:5432/disruption_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Apache HttpClient 5 for Feign HTTP PATCH support
spring.cloud.openfeign.httpclient.hc5.enabled=true